version: 1.0.{build}
image: Visual Studio 2019 Preview
build:
  verbosity: minimal
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true